// Taita Taveta institution roster (names + sub-county) extracted from the A2CT
// baseline survey workbooks. Static reference data for the IRENA Institutions tab.
export type Institution = { name: string; sub: string };
export type InstitutionGroup = { key: string; title: string; count: number; rows: Institution[] };

export const INSTITUTION_GROUPS: InstitutionGroup[] = [
  {
    key: "learning",
    title: "Learning Institutions",
    count: 196,
    rows: [
    { name: "Sowene secondary school", sub: "Taveta" },
    { name: "Dembwa Pre School", sub: "Mwatate" },
    { name: "St.Peters", sub: "Voi" },
    { name: "Kalela comprehensive school", sub: "Voi" },
    { name: "Voi St. Jude Educational Centre", sub: "Voi" },
    { name: "Josa Primary school", sub: "Mwatate" },
    { name: "Kidaya Ngerenyi Vtc", sub: "Mwatate" },
    { name: "MWANJILA VOCATIONAL TRAINING CENTRE", sub: "Mwatate" },
    { name: "MLAMBENYI VOCATIONAL TRAINING CENTRE", sub: "Mwatate" },
    { name: "Taita Taveta National Polytechnic", sub: "Voi" },
    { name: "Mwanyambo Pre-primary school", sub: "Voi" },
    { name: "Voi Primary school", sub: "Voi" },
    { name: "Mnamu Vocational Training", sub: "Mwatate" },
    { name: "Mnaru primary/JS", sub: "Mwatate" },
    { name: "Mnamu ECDE centre", sub: "Mwatate" },
    { name: "Voi Vocational Training Centre", sub: "Voi" },
    { name: "MWAMUNGA ECD", sub: "Voi" },
    { name: "Mwamunga Comprehensive School", sub: "Voi" },
    { name: "Ngolia Comprehensive school", sub: "Wundanyi" },
    { name: "Kitumbi Comprehensive school", sub: "Wundanyi" },
    { name: "Kitumbi High school", sub: "Wundanyi" },
    { name: "St.Marks Junior School", sub: "Wundanyi" },
    { name: "Chumvini vocational Training Centre", sub: "Taveta" },
    { name: "Chokaa comprehensive school", sub: "Taveta" },
    { name: "Sent Patrick Kimala cprehensive school", sub: "Taveta" },
    { name: "County Hills Junior school", sub: "Mwatate" },
    { name: "Lushangonyi primary", sub: "Wundanyi" },
    { name: "Msau VTC", sub: "Mwatate" },
    { name: "Iyale primary", sub: "Wundanyi" },
    { name: "Kighombo vocational training center", sub: "Mwatate" },
    { name: "Rong'e Juu vocational training centre", sub: "Mwatate" },
    { name: "Rong'e primary and Junior secondary school", sub: "Mwatate" },
    { name: "Mbauro ECD", sub: "Wundanyi" },
    { name: "Mbauro comprehensive", sub: "Wundanyi" },
    { name: "Kighombo comprehensive School", sub: "Mwatate" },
    { name: "Bethel Junior Academy", sub: "Voi" },
    { name: "Birikani Primary School", sub: "Voi" },
    { name: "Polaris Education centre", sub: "Voi" },
    { name: "St Mary's high school lushangonyi", sub: "Wundanyi" },
    { name: "Wesu ECD", sub: "Wundanyi" },
    { name: "Timbila special school", sub: "Taveta" },
    { name: "Njukini comprehensive", sub: "Taveta" },
    { name: "Lumi comprehensive", sub: "Taveta" },
    { name: "Sir Ramson Comprehensive", sub: "Taveta" },
    { name: "Priscilla Comprehensive School", sub: "Voi" },
    { name: "PRISCILLAH ECD", sub: "Voi" },
    { name: "MWaKiNGALI COMPREHENSIVE SCHOOL", sub: "Voi" },
    { name: "Mwakingali Ecd", sub: "Voi" },
    { name: "Mgambonyi High school", sub: "Wundanyi" },
    { name: "Wumingu Technical and vocational college", sub: "Wundanyi" },
    { name: "Nyache Vocational Training Center", sub: "Wundanyi" },
    { name: "Mokine Primary.", sub: "Taveta." },
    { name: "Mokine ECD.", sub: "Taveta" },
    { name: "Kambugu vocational training center.", sub: "Taveta" },
    { name: "Kitobo Secondary school", sub: "Taveta" },
    { name: "Kiwalwa Secondary School", sub: "Taveta" },
    { name: "Mahoo Mixed day & boarding integrated comprehensive school", sub: "Taveta" },
    { name: "Njoro mixed day school", sub: "Taveta" },
    { name: "Njoro day primary school", sub: "Taveta" },
    { name: "Timbila  Boarding and day comrehensive", sub: "Taveta" },
    { name: "Timbila Senior School", sub: "Taveta" },
    { name: "Sowene Comprehensive school", sub: "Taveta" },
    { name: "Khadija Muna Comprehensive\nSchool", sub: "Taveta" },
    { name: "Mwanyambo Special school for the deaf", sub: "Voi" },
    { name: "Mwangea Secondary School", sub: "Voi" },
    { name: "Voi pre-premary School", sub: "Voi" },
    { name: "Msheghesheni primary school", sub: "Taveta" },
    { name: "Mwatate technical and vocational training center", sub: "Mwatate" },
    { name: "Rekeke  primary school", sub: "Taveta" },
    { name: "Boma ecde", sub: "Wundanyi" },
    { name: "Mwachawaza VTC", sub: "Mwatate" },
    { name: "Mwachawaza ECDE", sub: "Mwatate" },
    { name: "Sungululu comprehensive", sub: "Wundanyi" },
    { name: "Mwandala primary school", sub: "Mwatate" },
    { name: "Mwatunge School", sub: "Mwatate" },
    { name: "Msisinenyi School", sub: "Mwatate" },
    { name: "Mwatate Primary", sub: "Mwatate" },
    { name: "Baby nest junior academy", sub: "Wundanyi" },
    { name: "St Ignatius nguraru primary", sub: "Wundanyi" },
    { name: "Mwagafwa vrc", sub: "Wundanyi" },
    { name: "Sungululu ecde", sub: "Wundanyi" },
    { name: "Malukiloriti mixed day secondary", sub: "Taveta" },
    { name: "Malukiloriti Primary and Junior School", sub: "Taveta" },
    { name: "Sowene Mixed Day secondary school", sub: "Taveta" },
    { name: "Wusi comprehensive", sub: "Mwatate" },
    { name: "Kishamba comprehensive School", sub: "Mwatate" },
    { name: "Lotima primary school.", sub: "Taveta" },
    { name: "Ngutini secondary school.", sub: "Taveta" },
    { name: "Kitoghoto primary school.", sub: "Taveta" },
    { name: "Eldoro High school", sub: "Taveta" },
    { name: "Mbuyuni sunrise academy", sub: "Taveya" },
    { name: "Kishushe Primary School", sub: "Wundanyi" },
    { name: "Kishushe Vocational Training Center", sub: "Wundanyi" },
    { name: "Mlilo Comprehensive School", sub: "Wundanyi" },
    { name: "Salaita Comprehensi School", sub: "Taveta" },
    { name: "Ikanga primary school", sub: "Voi" },
    { name: "Imani primary school", sub: "Voi" },
    { name: "Mahandakini comprehensive", sub: "Taveta" },
    { name: "Machungwani comprehensive", sub: "Taveta" },
    { name: "Chala vocational training centre", sub: "Taveta" },
    { name: "Sacred heart mwakiwiwi girls", sub: "Wundanyi" },
    { name: "St John high school", sub: "Wundanyi" },
    { name: "St James primary", sub: "Wundanyi" },
    { name: "Mwangea comprehensive", sub: "Wundanyi" },
    { name: "St Ann's elimu center", sub: "Wundanyi" },
    { name: "St John comprehensive", sub: "Wundanyi" },
    { name: "Mruru primary", sub: "Mwatate" },
    { name: "Kungu Primary School", sub: "Mwatate" },
    { name: "Grigan primary school", sub: "Taveta" },
    { name: "St. Joseph's ECD", sub: "Mwatate" },
    { name: "Mata comprehensive school", sub: "Taveta" },
    { name: "St Joseph secondary school", sub: "Mwatate" },
    { name: "Mata high school", sub: "Taveta" },
    { name: "Kidaya comprehensive School", sub: "Mwatate" },
    { name: "NDOME COMPREHENSIVE SCHOOL", sub: "Voi" },
    { name: "Ndome Ecd", sub: "Voi" },
    { name: "Mwaghogho Secondary School", sub: "Voi" },
    { name: "Mlundunyii Comprehensive School", sub: "Voi" },
    { name: "Mlundinyi Ecd", sub: "Voi" },
    { name: "Mwandisha primary school", sub: "Mwatate" },
    { name: "Kitivo ECDE", sub: "Mwatate" },
    { name: "Orkungugu comprehensive snhool", sub: "Taveta" },
    { name: "Ndii primary", sub: "Voi" },
    { name: "Manga ECDE", sub: "Voi" },
    { name: "John Mark senior secondary", sub: "Voi" },
    { name: "Jipe Comprehensive school", sub: "Taveta" },
    { name: "Mzwanenyi primary and junior school", sub: "Mwatate" },
    { name: "Sirienyi junior school", sub: "Mwatate" },
    { name: "Mwakitutu primary school", sub: "Mwatate" },
    { name: "County Hills ECDE", sub: "Mwatate" },
    { name: "Mrabani Primary School", sub: "Taveta" },
    { name: "Lake Jipe Based Academy", sub: "Taveta." },
    { name: "Madarasani primary school.", sub: "Taveta." },
    { name: "Riata Primary School", sub: "Taveta" },
    { name: "Nyache primary school", sub: "Wundanyi" },
    { name: "Kimangachughu comprehensive school", sub: "Wundanyi" },
    { name: "Maghimbinyi comprehensive school", sub: "Wundanyi" },
    { name: "Werugha comprehensive primary school", sub: "Wundanyi" },
    { name: "Canon Kituri secondary school", sub: "Wundanyi" },
    { name: "Kirumbi eliezer school", sub: "Voi" },
    { name: "Bright Angels Education centre", sub: "Voi" },
    { name: "Kirumbi Comprehensive school", sub: "Voi" },
    { name: "Kileva Eastfield comprehensive school", sub: "Voi" },
    { name: "New Whitehouse Academy", sub: "Voi" },
    { name: "Wisdom Academy", sub: "Voi" },
    { name: "Hidaya Edcd", sub: "Voi" },
    { name: "Bughuta Secondary school", sub: "Voi" },
    { name: "Bughuta primary", sub: "Voi" },
    { name: "Mkamenyi Primary School", sub: "Voi" },
    { name: "Kilulunyi primary", sub: "Mwatate" },
    { name: "Kilulunyi ECDE", sub: "Mwatate" },
    { name: "Mwambonu secondary school", sub: "Mwatate" },
    { name: "St.Bartholomew", sub: "Voi" },
    { name: "Shinning angel ecde", sub: "Taita taveta" },
    { name: "Ikanga Comprehensive", sub: "Voi" },
    { name: "Zare primary", sub: "Mwatate" },
    { name: "Zare ECDE", sub: "Mwatate" },
    { name: "St Paul's new model nursery school", sub: "Wundanyi" },
    { name: "Abori primary school", sub: "Taveta" },
    { name: "MAILIKUMI PRIMARY AND JUNIOR SCHOOL", sub: "Mwatate" },
    { name: "KIGHONONYI PRIMARY SCHOOL", sub: "Mwatate" },
    { name: "MARIWENYI PRIMARY SCHOOL", sub: "Mwatate" },
    { name: "Twin bird junior school", sub: "Wundanyi" },
    { name: "Kituma secondary", sub: "Mwatate" },
    { name: "St.Peter Hill view School", sub: "Voi" },
    { name: "Mnaoni ECDE Centre", sub: "Voi" },
    { name: "Gimba primary school", sub: "Voi" },
    { name: "Kaloleni mixed secondary school", sub: "Voi" },
    { name: "Kalambe comprehensive school", sub: "Voi" },
    { name: "Pillar of home academy", sub: "Voi" },
    { name: "Flower of camel", sub: "Voi" },
    { name: "Manyani primary and juniour", sub: "Voi" },
    { name: "Mdundonyi comprrhensive", sub: "Wundanyi" },
    { name: "Mdundonyi secondary", sub: "Wundanyi" },
    { name: "St Joseph's primary", sub: "Mwatate" },
    { name: "Mwanduka pre school", sub: "Mwatate" },
    { name: "Elijah mzae secondary", sub: "Mwatate" },
    { name: "Sowene primary school", sub: "taveta" },
    { name: "Sacred heart school", sub: "Taveta" },
    { name: "Dorry academy", sub: "Taveta" },
    { name: "Happy angels academy", sub: "Taveta" },
    { name: "Ulawani comprehensive school", sub: "Taveta" },
    { name: "Keynote academy", sub: "Taveta" },
    { name: "Taveta vocational training college", sub: "Taveta" },
    { name: "Mahoo Girls Secondary School", sub: "Taveta" },
    { name: "Shining Stars Academy", sub: "Taveta" },
    { name: "Mshekesheni Day Primary", sub: "Taveta" },
    { name: "Divine Favour Junior Academy", sub: "Taveta" },
    { name: "Kilimanjaro Premier Excellent Academy", sub: "Taveta" },
    { name: "Kavingoni Primary and ECD", sub: "Voi" },
    { name: "Mwambiti VTC", sub: "Voi" },
    { name: "Mwambiti Comprehensive", sub: "VOI" },
    { name: "Kajire primary", sub: "Voi" },
    { name: "Kajire Girls Senior School", sub: "Voi" },
    { name: "bahati nurser school", sub: "taveta" },
    { name: "alfatah academy", sub: "taveta" },
    ],
  },
  {
    key: "catering",
    title: "Catering Outlets (Hotels & SMEs)",
    count: 185,
    rows: [
    { name: "Galaxy Resort", sub: "Voi" },
    { name: "Lukundo", sub: "Voi" },
    { name: "Salaget hotel", sub: "Voi" },
    { name: "Imani hotel", sub: "Voi" },
    { name: "Anjelina hotel", sub: "Voi" },
    { name: "Joy Hotel", sub: "Mwatate" },
    { name: "Grace hotel", sub: "Mwatate" },
    { name: "Mama joice", sub: "Mwatate" },
    { name: "Pedu Grill", sub: "Mwatate" },
    { name: "Mama tamtam", sub: "Mwatate" },
    { name: "Dubai hotel", sub: "Mwatate" },
    { name: "Madrid hotel", sub: "Mwatate" },
    { name: "Ebeneza", sub: "Mwatate" },
    { name: "Mama faruk hotel", sub: "Mwatate" },
    { name: "Teachers base hotel", sub: "Mwatate" },
    { name: "Jahazi Swahili hotel", sub: "Voi" },
    { name: "Comrades park", sub: "Voi" },
    { name: "Mama ntilie", sub: "Voi" },
    { name: "Amis cafe", sub: "Voi" },
    { name: "Mama Faima", sub: "Voi" },
    { name: "Flames", sub: "Voi" },
    { name: "Elina Hotel", sub: "Voi" },
    { name: "Mzaramo Hotel", sub: "Voi" },
    { name: "Tamtam", sub: "Voi" },
    { name: "Utamu Hotel", sub: "Voi" },
    { name: "Junction", sub: "Mwatate" },
    { name: "Vero's hotel", sub: "Mwatate" },
    { name: "Santiago bar and restaurant", sub: "Mwatate" },
    { name: "Keyman hotel and accommodation", sub: "Mwatate" },
    { name: "Red Sea hotel", sub: "Mwatate" },
    { name: "Ferry Digital", sub: "Mwatate" },
    { name: "Mamake Jay", sub: "Mwatate" },
    { name: "Fridah Bakery", sub: "Mwatate" },
    { name: "Mashallah Swahili Dishes", sub: "Mwatate" },
    { name: "Zurick restaurant", sub: "Voi" },
    { name: "Favoured cafe", sub: "Voi" },
    { name: "Mama fatma", sub: "Voi" },
    { name: "Friends Hotel", sub: "Voi" },
    { name: "Sky base inn", sub: "Voi" },
    { name: "Ranch hotel", sub: "Taveta" },
    { name: "Swahili dishes hotel", sub: "Taveta" },
    { name: "Taveta fries", sub: "Taveta" },
    { name: "Mzedu Bar and Eatery", sub: "Voi" },
    { name: "Sahara Resort", sub: "Voi" },
    { name: "Neema Fish Cafe", sub: "Voi" },
    { name: "Masimbini Hotel", sub: "Voi" },
    { name: "Madina Cafe", sub: "Voi" },
    { name: "Dora's hotel", sub: "Wundanyi" },
    { name: "Mjasiri cafe", sub: "Wundanyi" },
    { name: "Mariam ibrahim", sub: "Wundanyi" },
    { name: "Mvumunyi", sub: "Wundanyi" },
    { name: "Mpaji ni Mungu", sub: "Mwatate" },
    { name: "Mums kitchen", sub: "Wundanyi" },
    { name: "Soup club", sub: "Wundanyi" },
    { name: "Mama Majala", sub: "Mwatate" },
    { name: "Janies hotel", sub: "Wundanyi" },
    { name: "Fine breez hotel", sub: "Wundanyi" },
    { name: "Delicious meals palace", sub: "Mwatate" },
    { name: "Feliz", sub: "Mwatate" },
    { name: "Mama Ben", sub: "Wundanyi" },
    { name: "Rose food center", sub: "Mwatate" },
    { name: "Market palace hotel", sub: "Taveta" },
    { name: "Roadside hotel", sub: "Taveta" },
    { name: "CUSTOMER THREE HOTEL", sub: "Taveta" },
    { name: "NANYORO HOTEL", sub: "Taveta" },
    { name: "MAYA FOODIES", sub: "Taveta" },
    { name: "MAMA SAMAKI", sub: "Taveta" },
    { name: "BARAKA HOTEL", sub: "Taveta" },
    { name: "Kilimanjaro view hotel", sub: "Taveta" },
    { name: "Downtown six planet hotel", sub: "Taveta" },
    { name: "Corner butcher", sub: "Taveta" },
    { name: "Fish hotel", sub: "Taveta" },
    { name: "Kivukoni eating house", sub: "Taveta" },
    { name: "Mamrema Dishes", sub: "Taveta" },
    { name: "Kwa Maria hotel.", sub: "Taveta" },
    { name: "Sam hotel", sub: "Taveta" },
    { name: "Eliza hotel", sub: "Taveta" },
    { name: "Canan Hotel", sub: "Taveta" },
    { name: "Oasis Hotel", sub: "Voi" },
    { name: "Wahomes", sub: "Voi" },
    { name: "Maghonyi pork centre", sub: "Voi" },
    { name: "Kuku Choma Base", sub: "Voi" },
    { name: "Jacob Muli", sub: "Voi" },
    { name: "Distar Hotel", sub: "Voi" },
    { name: "Home Boys Hotel", sub: "Voi" },
    { name: "Kythia's", sub: "Voi" },
    { name: "Road ways", sub: "Voi Town" },
    { name: "Sanguli Cafe", sub: "Voi" },
    { name: "Customer hotel", sub: "Taveta" },
    { name: "Bench Hotel cess", sub: "Taveya" },
    { name: "Nafuu Hotel", sub: "Taveta" },
    { name: "Mkuyuni Ho9", sub: "Taveta" },
    { name: "Mteule cafe", sub: "Wundanyi" },
    { name: "Chicago soop club", sub: "Wundanyi" },
    { name: "Kwa Manjenje hotel", sub: "Wundanyi" },
    { name: "Super Hotel", sub: "Wundanyi" },
    { name: "Neema Hotel", sub: "Wundanyi" },
    { name: "Supu Club", sub: "Mwatate" },
    { name: "Road side vendor, no name", sub: "Taitataveta" },
    { name: "5 star hotel.", sub: "Voi" },
    { name: "Tnah", sub: "Mwatate" },
    { name: "Elly's base", sub: "Wundanyi" },
    { name: "Starehe hotel", sub: "Taita taveta" },
    { name: "MMS HOTEL", sub: "Taita taveta" },
    { name: "Amigo's hotel", sub: "Mwatate" },
    { name: "Glory to  glory hotel", sub: "Mwatate" },
    { name: "Bongo hotel", sub: "Taita taveta" },
    { name: "Classic hotel", sub: "Wundanyi" },
    { name: "Parkviewhotel", sub: "Mwatate" },
    { name: "Arena hotel", sub: "Wundanyi" },
    { name: "Samaki fry base", sub: "Taita taveta" },
    { name: "Upendo cafe", sub: "Mwatate" },
    { name: "Mama sharifa Cafe", sub: "Mwatate" },
    { name: "Kibadaski", sub: "Mwatate" },
    { name: "Hotel", sub: "Mwatate" },
    { name: "Mama rose", sub: "Mwatate" },
    { name: "Calabash hotel", sub: "Voi" },
    { name: "Mama Ester", sub: "Voi" },
    { name: "Topsize hotel", sub: "Voi" },
    { name: "Estate hotel", sub: "Voi" },
    { name: "Kwa muindi", sub: "Voi" },
    { name: "Shasha hotel", sub: "Voi" },
    { name: "Rama kiosk", sub: "Voi" },
    { name: "Choma corner", sub: "Voi" },
    { name: "Farmers butchery", sub: "Taveta." },
    { name: "Kwa Amos hotel", sub: "Taveta" },
    { name: "Safina hotel", sub: "Taveta" },
    { name: "Nyaugenya hotel", sub: "Taveta" },
    { name: "Riverside hotel", sub: "Taveta" },
    { name: "St Mary's carnteen", sub: "Taita taveta" },
    { name: "Chill base soup", sub: "Mwatate" },
    { name: "Crasu hotel", sub: "Voi" },
    { name: "Corner hotel", sub: "Voi" },
    { name: "Travellers hotel", sub: "Voi" },
    { name: "Jazz hotel", sub: "Voi" },
    { name: "Benta hotel", sub: "Voi" },
    { name: "Mama Willy Hotel.", sub: "Taveta" },
    { name: "Magongo cafe", sub: "Wunday" },
    { name: "New life hotel", sub: "Wundanyi" },
    { name: "Mghambonyi Hotel", sub: "Wundanyi" },
    { name: "Modern cafe", sub: "Wundanyi" },
    { name: "Kitumbi Hotel", sub: "Wundanyi" },
    { name: "Endline hotel", sub: "Wundanyi" },
    { name: "Lukundo Hotel", sub: "Wundanyi" },
    { name: "Montez dishes", sub: "taveta" },
    { name: "Japan tours hotel", sub: "Taveta" },
    { name: "Dora hotel", sub: "taveta" },
    { name: "Highway hotel", sub: "Taveta" },
    { name: "Mama mwendee hotel", sub: "Taveta" },
    { name: "K2 MEALS HOTEL", sub: "Taveta" },
    { name: "Hidden Gem Hotel", sub: "Taveta" },
    { name: "PETE DISHES", sub: "Taveta" },
    { name: "P&G Hotel", sub: "Voi" },
    { name: "Awu's", sub: "Voi" },
    { name: "Malengo youth Hotel", sub: "Voi" },
    { name: "Joy Bringers Hotel", sub: "Voi" },
    { name: "Amani Cafe", sub: "Voi" },
    { name: "Anguo", sub: "Voi" },
    { name: "Me Dicky", sub: "Voi" },
    { name: "Ebenezer", sub: "Voi" },
    { name: "Tawakal Hotel", sub: "Mwatate" },
    { name: "Mama rodah Hotel", sub: "Mwatate" },
    { name: "Miami cafe Diaspora 24/7", sub: "Taveta" },
    { name: "Never give up Cafe", sub: "Taveta" },
    { name: "Mama Matilda cafe", sub: "Taveta" },
    { name: "Floriana Dishes", sub: "Mwatate" },
    { name: "Jane cafe", sub: "Mwatate" },
    { name: "Roadside kibanda, no name", sub: "Mwatate" },
    { name: "Tamutamu hotel", sub: "Mwatate" },
    { name: "Dmaz Hotel", sub: "Taveta" },
    { name: "Lukondo Bakery", sub: "Taveta" },
    { name: "Star foods.", sub: "Taveta" },
    { name: "Mama Sayo Hotel.", sub: "Taveta" },
    { name: "United Diary", sub: "Mwatate" },
    { name: "Big Tree", sub: "Voi" },
    { name: "Agape hotel", sub: "Voi" },
    { name: "Maendeleo cafe", sub: "Voi" },
    { name: "Mama Sweetie Hotel", sub: "Voi" },
    { name: "Coast Dishes", sub: "Voi" },
    { name: "Me Chao hotel", sub: "Voi" },
    { name: "Judy's hotel", sub: "Voi" },
    { name: "Kwa Aboo", sub: "Voi" },
    { name: "Food is life", sub: "Voi" },
    { name: "Nanyori hotel", sub: "Taveta" },
    { name: "Mama Lianah Takeaways", sub: "Taveta" },
    ],
  },
  {
    key: "health",
    title: "Health Facilities",
    count: 12,
    rows: [
    { name: "Mwatate Sub-County Hospital", sub: "Mwatate" },
    { name: "Njukini health centre", sub: "Taveta" },
    { name: "Joscare medical clinic center", sub: "Taveta" },
    { name: "Moi Referral Hospital", sub: "Voi" },
    { name: "Tsavo Comprehensive Hospital", sub: "Voi" },
    { name: "Dawida Annex Treatment and Rehabilitation Centre", sub: "Voi" },
    { name: "Ndovu health Centre", sub: "Voi" },
    { name: "St . Joseph shelter of hope", sub: "Voi" },
    { name: "The River Jordan Medical Centre", sub: "Voi" },
    { name: "Sandstone hospital", sub: "Taveta" },
    { name: "Wesu sub county", sub: "Wundanyi" },
    { name: "Mwatate", sub: "Mwatate" },
    ],
  },
  {
    key: "correctional",
    title: "Correctional Institutions",
    count: 5,
    rows: [
    { name: "Taveta prison", sub: "Taveta" },
    { name: "Wundanyi main prison", sub: "Wundanyi" },
    { name: "Wundanyi women prison", sub: "Wundanyi" },
    { name: "Manyani prison", sub: "Voi" },
    { name: "Voi prison", sub: "Voi" },
    ],
  },
];
