// Config-driven resource registry. Each entry generates a full CRUD screen
// (list + search + slide-over create/edit + soft-delete) via <ResourceView>,
// honouring the same "Add button" contract as the hand-built Parties module.
// Codes (PR-/PO-/…) are auto-generated by DB triggers, so they're not form fields.

export type FieldType = "text" | "textarea" | "number" | "money" | "date" | "select" | "ref";

export type RefSpec = { table: string; labelKey: string; typeFilter?: string };

export type Field = {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[]; // for select
  ref?: RefSpec; // for ref
  half?: boolean; // render two-per-row
};

export type Column = {
  key: string;
  label: string;
  kind?: "text" | "badge" | "money" | "date";
};

export type Resource = {
  slug: string;
  table: string;
  module: string; // permission prefix
  group: string;
  title: string;
  subtitle: string;
  /** If set, the resource IS a spine party of this type (table = "parties"). */
  partyType?: string;
  select: string;
  orderBy?: string;
  columns: Column[];
  fields: Field[];
};

const STATUS: Column = { key: "status", label: "Status", kind: "badge" };

export const RESOURCES: Resource[] = [
  // ---------------- Phase 2 — Procure-to-Pay ----------------
  {
    slug: "vendors", table: "parties", module: "procurement", partyType: "vendor",
    group: "Procure-to-Pay", title: "Vendors", subtitle: "Suppliers Ignis buys from — one spine party each.",
    select: "id,display_name,legal_name,kra_pin,email,phone,status,created_at",
    columns: [
      { key: "display_name", label: "Name" },
      { key: "kra_pin", label: "KRA PIN" },
      { key: "email", label: "Email" },
      STATUS,
      { key: "created_at", label: "Added", kind: "date" },
    ],
    fields: [
      { key: "display_name", label: "Display name", type: "text", required: true },
      { key: "legal_name", label: "Legal name", type: "text" },
      { key: "kra_pin", label: "KRA PIN", type: "text", half: true },
      { key: "phone", label: "Phone", type: "text", half: true },
      { key: "email", label: "Email", type: "text" },
    ],
  },
  // Requisitions & Purchase Orders have dedicated workflow pages under
  // /procurement (lines, approvals, GRN, three-way match) — see lib/spine/nav.ts.

  // ---------------- Phase 3 — Revenue ----------------
  {
    slug: "customers", table: "parties", module: "revenue", partyType: "customer",
    group: "Revenue", title: "Customers", subtitle: "Institutions Ignis sells to or serves.",
    select: "id,display_name,legal_name,kra_pin,email,phone,status,created_at",
    columns: [
      { key: "display_name", label: "Name" },
      { key: "kra_pin", label: "KRA PIN" },
      { key: "email", label: "Email" },
      STATUS,
      { key: "created_at", label: "Added", kind: "date" },
    ],
    fields: [
      { key: "display_name", label: "Display name", type: "text", required: true },
      { key: "legal_name", label: "Legal name", type: "text" },
      { key: "kra_pin", label: "KRA PIN", type: "text", half: true },
      { key: "phone", label: "Phone", type: "text", half: true },
      { key: "email", label: "Email", type: "text" },
    ],
  },
  {
    slug: "quotations", table: "quotations", module: "revenue",
    group: "Revenue", title: "Quotations", subtitle: "Quote builder with versioning and conversion to sales orders.",
    select: "id,code,version,valid_until,status,total_minor,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "version", label: "v" },
      { key: "total_minor", label: "Total", kind: "money" },
      { key: "valid_until", label: "Valid until", kind: "date" },
      STATUS,
    ],
    fields: [
      { key: "customer_party_id", label: "Customer", type: "ref", ref: { table: "parties", labelKey: "display_name", typeFilter: "customer" }, required: true },
      { key: "total_minor", label: "Total", type: "money", half: true },
      { key: "valid_until", label: "Valid until", type: "date", half: true },
      { key: "status", label: "Status", type: "select", options: ["draft", "sent", "accepted", "declined", "converted"] },
    ],
  },
  {
    slug: "ar-invoices", table: "receivable_invoices", module: "revenue",
    group: "Revenue", title: "Sales Invoices", subtitle: "Receivables with KRA eTIMS compliance.",
    select: "id,code,invoice_date,due_date,amount_minor,etims_status,status,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "amount_minor", label: "Amount", kind: "money" },
      { key: "due_date", label: "Due", kind: "date" },
      { key: "etims_status", label: "eTIMS", kind: "badge" },
      STATUS,
    ],
    fields: [
      { key: "customer_party_id", label: "Customer", type: "ref", ref: { table: "parties", labelKey: "display_name", typeFilter: "customer" }, required: true },
      { key: "amount_minor", label: "Amount", type: "money", half: true },
      { key: "tax_minor", label: "Tax", type: "money", half: true },
      { key: "invoice_date", label: "Invoice date", type: "date", half: true },
      { key: "due_date", label: "Due date", type: "date", half: true },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "paid", "overdue"] },
    ],
  },

  // ---------------- Phase 4 — People ----------------
  {
    slug: "employees", table: "parties", module: "people", partyType: "employee",
    group: "People", title: "Employees", subtitle: "Employee records (statutory fields on the profile).",
    select: "id,display_name,kra_pin,email,phone,status,created_at",
    columns: [
      { key: "display_name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      STATUS,
      { key: "created_at", label: "Joined", kind: "date" },
    ],
    fields: [
      { key: "display_name", label: "Full name", type: "text", required: true },
      { key: "email", label: "Email", type: "text", half: true },
      { key: "phone", label: "Phone", type: "text", half: true },
      { key: "kra_pin", label: "KRA PIN", type: "text" },
    ],
  },
  {
    slug: "leave", table: "leave_applications", module: "people",
    group: "People", title: "Leave Application", subtitle: "Apply, auto-calc working days, route for approval.",
    select: "id,start_date,end_date,days,status,created_at",
    columns: [
      { key: "start_date", label: "From", kind: "date" },
      { key: "end_date", label: "To", kind: "date" },
      { key: "days", label: "Days" },
      STATUS,
      { key: "created_at", label: "Filed", kind: "date" },
    ],
    fields: [
      { key: "employee_party_id", label: "Employee", type: "ref", ref: { table: "parties", labelKey: "display_name", typeFilter: "employee" }, required: true },
      { key: "type_id", label: "Leave type", type: "ref", ref: { table: "leave_types", labelKey: "name" }, required: true },
      { key: "start_date", label: "Start", type: "date", half: true },
      { key: "end_date", label: "End", type: "date", half: true },
      { key: "days", label: "Days", type: "number" },
    ],
  },

  // ---------------- Phase 5 — Assets ----------------
  {
    slug: "assets", table: "assets", module: "assets",
    group: "Assets", title: "Asset Register", subtitle: "Every cooker/utility/laptop with serial, location, custodian.",
    select: "id,code,name,serial_no,status,nbv_minor,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "serial_no", label: "Serial" },
      { key: "nbv_minor", label: "NBV", kind: "money" },
      STATUS,
    ],
    fields: [
      { key: "name", label: "Asset name", type: "text", required: true },
      { key: "category_id", label: "Category", type: "ref", ref: { table: "categories", labelKey: "name" }, half: true },
      { key: "serial_no", label: "Serial no", type: "text", half: true },
      { key: "location_id", label: "Location", type: "ref", ref: { table: "locations", labelKey: "name" }, half: true },
      { key: "cost_minor", label: "Cost", type: "money", half: true },
      { key: "status", label: "Status", type: "select", options: ["in_store", "deployed", "maintenance", "disposed"] },
    ],
  },
  {
    slug: "work-orders", table: "work_orders", module: "assets",
    group: "Assets", title: "Work Orders", subtitle: "Scheduled and ad-hoc maintenance jobs.",
    select: "id,code,type,status,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "type", label: "Type" },
      STATUS,
      { key: "created_at", label: "Raised", kind: "date" },
    ],
    fields: [
      { key: "asset_id", label: "Asset", type: "ref", ref: { table: "assets", labelKey: "name" }, required: true },
      { key: "type", label: "Type", type: "text", half: true },
      { key: "assignee_user_id", label: "Assignee", type: "ref", ref: { table: "users", labelKey: "full_name" }, half: true },
      { key: "status", label: "Status", type: "select", options: ["open", "in_progress", "done", "cancelled"] },
    ],
  },

  // ---------------- Phase 6 — Projects ----------------
  {
    slug: "milestones", table: "milestones", module: "projects",
    group: "Projects", title: "Milestones", subtitle: "Deliverables and funder reporting checkpoints.",
    select: "id,name,due_date,status,created_at",
    columns: [
      { key: "name", label: "Milestone" },
      { key: "due_date", label: "Due", kind: "date" },
      STATUS,
    ],
    fields: [
      { key: "project_id", label: "Project", type: "ref", ref: { table: "projects", labelKey: "name" }, required: true },
      { key: "name", label: "Milestone", type: "text", required: true },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["pending", "in_progress", "done", "overdue"] },
    ],
  },

  // ---------------- Phase 7 — CRM ----------------
  {
    slug: "engagements", table: "engagements", module: "crm",
    group: "CRM", title: "Engagements", subtitle: "One row per partner relationship — the heart of the CRM.",
    select: "id,code,title,stage,priority,status,next_action,due_by,view,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "title", label: "Name" },
      { key: "stage", label: "Stage", kind: "badge" },
      { key: "view", label: "View", kind: "badge" },
      { key: "next_action", label: "Next action" },
      { key: "due_by", label: "Due", kind: "date" },
    ],
    fields: [
      { key: "title", label: "Engagement name", type: "text" },
      { key: "partner_party_id", label: "Partner", type: "ref", ref: { table: "parties", labelKey: "display_name", typeFilter: "partner" }, required: true },
      { key: "view", label: "View", type: "select", options: ["upstream", "downstream"], half: true },
      { key: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "critical"], half: true },
      { key: "stage", label: "Stage", type: "text" },
      { key: "next_action", label: "Next action", type: "text" },
      { key: "due_by", label: "Due by", type: "date" },
    ],
  },
  {
    slug: "opportunities", table: "opportunities", module: "crm",
    group: "CRM", title: "Opportunities", subtitle: "Funding calls, RFPs and climate-finance windows.",
    select: "id,title,type,deadline,status,created_at",
    columns: [
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "deadline", label: "Deadline", kind: "date" },
      STATUS,
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "funder_party_id", label: "Funder", type: "ref", ref: { table: "parties", labelKey: "display_name", typeFilter: "partner" }, half: true },
      { key: "type", label: "Type", type: "text", half: true },
      { key: "deadline", label: "Deadline", type: "date", half: true },
      { key: "source_url", label: "Source URL", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["open", "pursuing", "submitted", "won", "lost", "closed"] },
    ],
  },

  {
    slug: "partners", table: "parties", module: "crm", partyType: "partner",
    group: "CRM", title: "Partners", subtitle: "Funders, investors, government & institutional partners.",
    select: "id,display_name,legal_name,kra_pin,email,phone,status,created_at",
    columns: [
      { key: "display_name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      STATUS,
      { key: "created_at", label: "Added", kind: "date" },
    ],
    fields: [
      { key: "display_name", label: "Display name", type: "text", required: true },
      { key: "legal_name", label: "Legal name", type: "text" },
      { key: "kra_pin", label: "KRA PIN", type: "text", half: true },
      { key: "phone", label: "Phone", type: "text", half: true },
      { key: "email", label: "Email", type: "text" },
    ],
  },

  // ---------------- Phase 9 — Governance ----------------
  {
    slug: "contracts", table: "contracts", module: "governance",
    group: "Governance", title: "Contracts", subtitle: "Every MoU/NDA/supplier/employment contract with expiry alerts.",
    select: "id,code,type,start_date,end_date,value_minor,status,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "type", label: "Type" },
      { key: "end_date", label: "Expires", kind: "date" },
      { key: "value_minor", label: "Value", kind: "money" },
      STATUS,
    ],
    fields: [
      { key: "type", label: "Type", type: "text", required: true, half: true },
      { key: "counterparty_party_id", label: "Counterparty", type: "ref", ref: { table: "parties", labelKey: "display_name" }, half: true },
      { key: "start_date", label: "Start", type: "date", half: true },
      { key: "end_date", label: "End", type: "date", half: true },
      { key: "value_minor", label: "Value", type: "money" },
      { key: "status", label: "Status", type: "select", options: ["draft", "active", "expired", "terminated"] },
    ],
  },
  {
    slug: "risks", table: "risks", module: "governance",
    group: "Governance", title: "Risk Register", subtitle: "Likelihood × impact scoring with owners and mitigations.",
    select: "id,description,likelihood,impact,score,status,created_at",
    columns: [
      { key: "description", label: "Risk" },
      { key: "score", label: "Score", kind: "badge" },
      STATUS,
    ],
    fields: [
      { key: "description", label: "Description", type: "textarea", required: true },
      { key: "likelihood", label: "Likelihood (1-5)", type: "number", half: true },
      { key: "impact", label: "Impact (1-5)", type: "number", half: true },
      { key: "mitigation", label: "Mitigation", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "mitigating", "closed"] },
    ],
  },
  {
    slug: "compliance", table: "compliance_obligations", module: "governance",
    group: "Governance", title: "Compliance Calendar", subtitle: "KRA, NSSF, SHIF, statutory returns and renewals.",
    select: "id,name,authority,frequency,next_due,status,created_at",
    columns: [
      { key: "name", label: "Obligation" },
      { key: "authority", label: "Authority" },
      { key: "next_due", label: "Next due", kind: "date" },
      STATUS,
    ],
    fields: [
      { key: "name", label: "Obligation", type: "text", required: true },
      { key: "authority", label: "Authority", type: "text", half: true },
      { key: "frequency", label: "Frequency", type: "text", half: true },
      { key: "next_due", label: "Next due", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["pending", "filed", "overdue"] },
    ],
  },

  // ---------------- Phase 10 — Field & Portals ----------------
  {
    slug: "tickets", table: "support_tickets", module: "field",
    group: "Field & Portals", title: "Support Tickets", subtitle: "Institutions raise issues against their deployments.",
    select: "id,code,subject,priority,status,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "subject", label: "Subject" },
      { key: "priority", label: "Priority", kind: "badge" },
      STATUS,
    ],
    fields: [
      { key: "institution_id", label: "Institution", type: "ref", ref: { table: "institutions", labelKey: "name" }, required: true },
      { key: "subject", label: "Subject", type: "text", required: true },
      { key: "body", label: "Details", type: "textarea" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "urgent"], half: true },
      { key: "status", label: "Status", type: "select", options: ["open", "in_progress", "resolved", "closed"], half: true },
    ],
  },

  // ---------------- Phase 8 — Intelligence ----------------
  {
    slug: "kpis", table: "kpis", module: "intelligence",
    group: "Intelligence", title: "KPIs", subtitle: "Metric definitions, targets and automated calculation.",
    select: "id,name,formula,target,module_source,created_at",
    columns: [
      { key: "name", label: "KPI" },
      { key: "target", label: "Target" },
      { key: "module_source", label: "Source" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "formula", label: "Formula", type: "text" },
      { key: "target", label: "Target", type: "number", half: true },
      { key: "module_source", label: "Source module", type: "text", half: true },
    ],
  },
  {
    slug: "impact", table: "impact_metrics", module: "intelligence",
    group: "Intelligence", title: "Impact Metrics", subtitle: "Emissions reduced, institutions served, staff trained.",
    select: "id,type,value,period,public_visible,created_at",
    columns: [
      { key: "type", label: "Metric" },
      { key: "value", label: "Value" },
      { key: "period", label: "Period" },
      { key: "created_at", label: "Recorded", kind: "date" },
    ],
    fields: [
      { key: "type", label: "Metric type", type: "text", required: true },
      { key: "value", label: "Value", type: "number", half: true },
      { key: "period", label: "Period", type: "text", half: true },
      { key: "project_id", label: "Project", type: "ref", ref: { table: "projects", labelKey: "name" } },
    ],
  },

  // ---------------- Phase 11 — Business Development ----------------
  {
    slug: "concepts", table: "concepts", module: "bd",
    group: "Business Development", title: "Concept Notes", subtitle: "Draft → review → submitted → won/lost, grounded in real data.",
    select: "id,code,title,status,created_at",
    columns: [
      { key: "code", label: "Code" },
      { key: "title", label: "Title" },
      STATUS,
      { key: "created_at", label: "Created", kind: "date" },
    ],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "opportunity_id", label: "Opportunity", type: "ref", ref: { table: "opportunities", labelKey: "title" } },
      { key: "assigned_to", label: "Assigned to", type: "ref", ref: { table: "users", labelKey: "full_name" } },
      { key: "status", label: "Status", type: "select", options: ["draft", "review", "submitted", "won", "lost"] },
    ],
  },
];

export function getResource(slug: string): Resource | undefined {
  return RESOURCES.find((r) => r.slug === slug);
}
